version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 07102004h
      POSTGRES_DB: defectdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MODEL_PATH: /app/model
    ports:
      - '8001:8001'
    volumes:
      - ./ai-service/model:/app/model

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - ai-service
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      AI_SERVICE_URL: ${AI_SERVICE_URL}
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - '8000:8000'
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8000/api
    ports:
      - '3000:3000'

volumes:
  db_data:
